version: "3.3"

networks:
    myyoutube:
        driver: bridge

services: 
    app:
        build:
            args:
                user: ducky
                uid: 1000
            context: ./container/laravel_api
            dockerfile: dockerfile
        image: myyoutube
        restart: unless-stopped
        working_dir: /var/www
        container_name: laravel_api
        depends_on: 
            - db
        ports: 
            - 8000:8000
            - 8001:3360
        volumes:
            - ./MyApi:/var/www
        networks: 
            - myyoutube

    db: 
        build: ./container/mysql/
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: mysql_db
        networks: 
            - myyoutube
        environment: 
            MYSQL_DATABASE: myapi
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: duck
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports: 
        - "3360:3306"
        restart: on-failure
        volumes: 
        - "./container/mysql/data:/var/lib/mysql"

    adminer: 
        image: adminer
        container_name: adminer_mysql
        networks: 
            - myyoutube
        ports: 
        - "9040:8080"
        restart: on-failure

    # nginx:
    #     image: nginx:1.17-alpine
    #     container_name: nginx
    #     restart: unless-stopped
    #     ports:
    #         - 8000:80
    #     volumes:
    #         - ./MyApi:/var/www
    #         - ./container/nginx:/etc/nginx/conf.d
    #     networks:
    #         - myyoutube