version: "3.3"

networks:
    myyoutube:
        driver: bridge

services: 
    app:
        build:
            args:
                user: ducky
                uid: 1000
            context: ./container/laravel_api
            dockerfile: dockerfile
        image: myyoutube
        restart: unless-stopped
        working_dir: /var/www
        container_name: laravel_api
        depends_on: 
            - db
        ports: 
            - 8000:8000
        volumes:
            - ./MyApi:/var/www
        networks: 
            - myyoutube

    db: 
        build: ./container/mysql/
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: mysql_db
        networks: 
            - myyoutube
        environment: 
            MYSQL_DATABASE: myapi
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: duck
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports: 
        - "3360:3306"
        restart: on-failure
        volumes: 
        - "./container/mysql/data:/var/lib/mysql"

    nuxt:
        build: ./container/nuxtjs/
        container_name: nuxtjs
        restart: on-failure
        networks: 
            - myyoutube
        volumes: 
            - "./nodejs:/usr/src/nuxt-app/"
        ports: 
            - 3000:3000

    elasticsearch:
        image: elasticsearch:7.13.2
        container_name: ELK
        networks: 
            - myyoutube
        ports: 
            - "9200:9200"
        environment: 
            - discovery.type=single-node
        ulimits: 
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./container/elasticsearch:/usr/share/elasticsearch/data

    kibana:
        image: kibana:7.9.2
        container_name: kibana
        networks:
            - myyoutube
        ports:
            - '5601:5601'

    encoding:
        build: ./container/encoding
        container_name: encoding_vdo
        networks: 
            - myyoutube
        ports: 
            - "6000:5000"
        volumes: 
            - "./encoding_video:/usr/src/app"
            - "./MyApi/storage/app/public:/usr/src/storage"

    postfix:
        build: ./container/postfix
        container_name: postfix
        networks: 
            - myyoutube
        ports:
            - "5185:185"
            - "5001:5000"
        tty: true
        volumes: 
            - "./postfix:/usr/src/app"
