FROM php:7.4-fpm

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer


# Set working directory
WORKDIR /var/www

RUN cat /usr/local/etc/php/php.ini-development | sed "s/max_file_uploads = 20/max_file_uploads = 25/g" | sed "s/memory_limit = 128M/memory_limit = 200M/g" | sed "s/post_max_size = 8M/post_max_size = 200M/g" | sed "s/upload_max_filesize = 2M/upload_max_filesize = 200M/g" > /tmp/php.ini 

RUN cat /tmp/php.ini > /usr/local/etc/php/php.ini-development
RUN cp /tmp/php.ini /usr/local/etc/php/conf.d/php.ini


CMD php artisan serve --host=0.0.0.0 --port=8000

EXPOSE 8000